language: php

services:
  - mysql

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

php:
  - 7.2

env:
  - LARAVEL_VERSION=5.8.*

before_install:
  - travis_retry composer self-update --stable -n
  - composer validate --no-check-all --strict
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - mysql -u root -e 'CREATE DATABASE ssn-test;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON ssn-test.* TO 'root'@'localhost';"

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o
  - travis_retry composer require --dev satooshi/php-coveralls

script:
  - vendor/bin/phpunit
